### ISSUE TITLE
Request for new functions

### ISSUE THREAD

**Issue by Xliff** [FCO/RakuAST-Matcher#2]
ANY-PARAMETER-NAMED 
ANY-FUNCTION-WITH-PARAMETER-NAMED

@FCO - You have the most interesting writing style, and it seems you are comfortable doing a lot of your work in signatures. It makes for some of the more strangely elegant code I've ever seen!

How would you go about implementing the above 2 functions. I thought I had some idea as to how things worked, but my attempts didn't pan out.

Thanks!

**Comment by FCO** [comment]
Thank you very much!

I’ll try to give it a try this weekend. I’ll let you know how it goes.

**Comment by FCO** [comment]
I have created a new module with a different approach for this same problem, I think the new way is easier and more understandable than this one, please take a look ate that new one and let me know if that's a good alternative, the name of this new module is ASTQuery (http://github.com/FCO/ASTQuery)
